version: '3.2'
services:
  eslint-config-policygenius:
    build: .
    volumes:
      - .:/go/src/github.com/buildkite/agent
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
    environment:
      - BUILDKITE
      - BUILDKITE_COMMIT
      - BUILDKITE_BRANCH
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_REPO
      - BUILDKITE_BUILD_ID=$BUILDKITE_BUILD_ID
      - BUILDKITE_AGENT_ACCESS_TOKEN=$BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_NUMBER
      - NPM_TOKEN
